version: '3'

services:
  portainer:
    image: dpage/pgadmin4
    ports:
      - 9101:80
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@localhost}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./storage/:/var/lib/pgadmin/storage/
      - ./home/:/home/
